[build]
cmd = "go build -o ./tmp/main ./cmd/server/"  # Cross-platform build command
bin = "./tmp/main"                            # Cross-platform binary path
include_ext = ["go", "tmpl", "html"]          # File extensions to watch
exclude_dir = ["vendor", "tmp", "valkey-data"] # Directories to exclude
