services:
  redis:
    image: redis:alpine
    container_name: firecast-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - firecast-network
    restart: unless-stopped

  firecast-server:
    image: ghcr.io/yggdrion/firecast/server:latest
    container_name: firecast-server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - firecast-network
    restart: unless-stopped

  firecast-client:
    image: ghcr.io/yggdrion/firecast/client:latest
    container_name: firecast-client
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      - SERVER_URL=http://firecast-server:8080
    depends_on:
      - redis
      - firecast-server
    networks:
      - firecast-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  firecast-network:
    driver: bridge
