version: "3.8"

services:
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - ./valkey-data:/data
    command: valkey-server --appendonly yes
