name: 📚 Spelling and Typos

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  CLICOLOR: 1

jobs:
  typos-spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Spell Check Repo
        uses: crate-ci/typos@52bd719c2c91f9d676e2aa359fc8e0db8925e6d8
